//
//  InventoryReportContent.swift
//  InventoryV3
//
//  Created by Marcus Deuß on 09.03.26.
//
//  NOTE: This view is rendered by ImageRenderer — no ScrollView,
//  no lazy containers, no materials. Solid colors only.
//

import SwiftUI

// MARK: - Top-level report view

struct InventoryReportContent: View {
    let items: [InventoryItem]

    private var totalValue: Double { items.reduce(0) { $0 + $1.price } }

    private var groupedByRoom: [(room: Room?, items: [InventoryItem])] {
        let dict = Dictionary(grouping: items) { $0.room }
        return dict
            .sorted { a, b in
                switch (a.key?.name, b.key?.name) {
                case (let n1?, let n2?): return n1 < n2
                case (nil, _): return false
                case (_, nil): return true
                }
            }
            .map { (room: $0.key, items: $0.value.sorted { $0.name < $1.name }) }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            reportHeader
            ForEach(groupedByRoom, id: \.room?.name) { group in
                roomSection(room: group.room, items: group.items)
            }
            reportFooter
        }
        .background(.white)
    }

    // MARK: - Header

    private var reportHeader: some View {
        HStack(spacing: 16) {
            AppLogoView(size: 56)

            VStack(alignment: .leading, spacing: 2) {
                Text("Inventory Report")
                    .font(.title2).bold()
                    .foregroundStyle(.white)
                Text(Date.now.formatted(date: .long, time: .omitted))
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.75))
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 2) {
                Text("\(items.count) items")
                    .font(.title3).bold()
                    .foregroundStyle(.white)
                Text(totalValue, format: .currency(code: Locale.current.currency?.identifier ?? "USD"))
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.75))
            }
        }
        .padding(20)
        .background(
            LinearGradient(
                stops: [
                    .init(color: Color(red: 0.22, green: 0.10, blue: 0.60), location: 0),
                    .init(color: Color(red: 0.05, green: 0.32, blue: 0.78), location: 1)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
        )
    }

    // MARK: - Room sections

    private func roomSection(room: Room?, items: [InventoryItem]) -> some View {
        VStack(alignment: .leading, spacing: 0) {
            // Section header bar
            HStack(spacing: 8) {
                if let data = room?.photoData, let uiImage = UIImage(data: data) {
                    Image(uiImage: uiImage)
                        .resizable()
                        .scaledToFill()
                        .frame(width: 22, height: 22)
                        .clipShape(.circle)
                } else {
                    Image(systemName: room?.sfSymbol ?? "house")
                        .foregroundStyle(.white)
                        .font(.system(size: 13))
                }
                Text(room?.name ?? "Unassigned")
                    .bold()
                    .foregroundStyle(.white)
                    .font(.subheadline)
                Spacer()
                Text("^[\(items.count) item](inflect: true)")
                    .foregroundStyle(.white.opacity(0.80))
                    .font(.caption)
            }
            .padding(.horizontal, 14)
            .padding(.vertical, 7)
            .background(Color(red: 0.28, green: 0.12, blue: 0.72).opacity(0.82))

            // Item rows
            ForEach(Array(items.enumerated()), id: \.element.id) { index, item in
                ReportItemRow(item: item, isAlternate: index.isMultiple(of: 2))
                if index < items.count - 1 {
                    Divider().padding(.leading, 58)
                }
            }
        }
    }

    // MARK: - Footer

    private var reportFooter: some View {
        HStack {
            Text("Generated by Inventory")
                .foregroundStyle(Color(red: 0.28, green: 0.12, blue: 0.72))
            Spacer()
            Text(Date.now.formatted(date: .abbreviated, time: .shortened))
        }
        .font(.caption)
        .foregroundStyle(.secondary)
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(Color(red: 0.95, green: 0.95, blue: 0.98))
    }
}

// MARK: - Item row

private struct ReportItemRow: View {
    let item: InventoryItem
    let isAlternate: Bool

    var body: some View {
        HStack(spacing: 10) {
            thumbnail
            info
            Spacer()
            priceStack
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 9)
        .background(isAlternate ? Color(red: 0.96, green: 0.96, blue: 1.00) : .white)
    }

    private var thumbnail: some View {
        Group {
            if let data = item.imageData, let uiImage = UIImage(data: data) {
                Image(uiImage: uiImage)
                    .resizable()
                    .scaledToFill()
            } else {
                ZStack {
                    Color(red: 0.28, green: 0.12, blue: 0.72).opacity(0.10)
                    Image(systemName: item.category?.sfSymbol ?? "square.grid.2x2")
                        .foregroundStyle(Color(red: 0.28, green: 0.12, blue: 0.72))
                        .font(.system(size: 15))
                }
            }
        }
        .frame(width: 34, height: 34)
        .clipShape(.rect(cornerRadius: 6))
    }

    private var info: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(item.name.isEmpty ? "Unnamed" : item.name)
                .bold()
                .font(.subheadline)
                .foregroundStyle(.primary)
            HStack(spacing: 4) {
                if let category = item.category {
                    Label(category.name, systemImage: category.sfSymbol)
                }
                if let brand = item.brand {
                    Text("·")
                    Text(brand.name)
                }
            }
            .font(.caption)
            .foregroundStyle(.secondary)
        }
    }

    private var priceStack: some View {
        VStack(alignment: .trailing, spacing: 2) {
            Text(item.price, format: .currency(code: Locale.current.currency?.identifier ?? "USD"))
                .bold()
                .font(.subheadline)
            if item.warrantyMonths > 0 {
                Text("\(item.warrantyMonths) mo. warranty")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }
}
