//
//  InventoryReportContent.swift
//  InventoryV3
//
//  Created by Marcus Deuß on 09.03.26.
//
//  NOTE: This view is rendered by ImageRenderer — no ScrollView,
//  no lazy containers, no materials. Solid colors only.
//
// Copyright 2026 Marcus Deuß
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


import SwiftUI
import SwiftData

// MARK: - Report Header

private struct ReportHeader: View {
    let items: [InventoryItem]

    private var totalValue: Double { items.reduce(0) { $0 + $1.price } }

    var body: some View {
        HStack(spacing: 16) {
            AppLogoView(size: 56)

            VStack(alignment: .leading, spacing: 2) {
                Text("Inventory Report")
                    .font(.title2).bold()
                    .foregroundStyle(.white)
                Text(Date.now.formatted(date: .long, time: .omitted))
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.75))
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 2) {
                Text("\(items.count) items")
                    .font(.title3).bold()
                    .foregroundStyle(.white)
                Text(totalValue, format: .currency(code: Locale.current.currency?.identifier ?? "USD"))
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.75))
            }
        }
        .padding(20)
        .background(
            LinearGradient(
                stops: [
                    .init(color: Color(red: 0.22, green: 0.10, blue: 0.60), location: 0),
                    .init(color: Color(red: 0.05, green: 0.32, blue: 0.78), location: 1)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
        )
    }
}

// MARK: - Report Footer

private struct ReportFooter: View {
    var body: some View {
        HStack {
            Text("Generated by Inventory")
                .foregroundStyle(Color(red: 0.28, green: 0.12, blue: 0.72))
            Spacer()
            Text(Date.now.formatted(date: .abbreviated, time: .shortened))
                .foregroundStyle(Color(red: 0.30, green: 0.30, blue: 0.30))
        }
        .font(.caption)
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(Color(red: 0.95, green: 0.95, blue: 0.98))
    }
}

// MARK: - PDF Per-Page Header

struct PDFPageHeader: View {
    let items: [InventoryItem]
    let pageIndex: Int
    let pageCount: Int

    var body: some View {
        HStack(spacing: 12) {
            AppLogoView(size: 32)

            VStack(alignment: .leading, spacing: 1) {
                Text("Inventory Report")
                    .bold()
                    .font(.subheadline)
                    .foregroundStyle(.white)
                Text(Date.now.formatted(date: .long, time: .omitted))
                    .font(.caption2)
                    .foregroundStyle(.white.opacity(0.80))
            }

            Spacer()

            Text("Page \(pageIndex + 1) of \(pageCount)")
                .bold()
                .font(.subheadline)
                .foregroundStyle(.white)
        }
        .padding(.horizontal, 16)
        .padding(.vertical, 10)
        .background(
            LinearGradient(
                stops: [
                    .init(color: Color(red: 0.22, green: 0.10, blue: 0.60), location: 0),
                    .init(color: Color(red: 0.05, green: 0.32, blue: 0.78), location: 1)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )
        )
    }
}

// MARK: - PDF Per-Page Footer

struct PDFPageFooter: View {
    let pageIndex: Int
    let pageCount: Int

    var body: some View {
        HStack {
            Text("Generated by Inventory")
                .foregroundStyle(Color(red: 0.28, green: 0.12, blue: 0.72))
            Spacer()
            Text("Page \(pageIndex + 1) of \(pageCount)")
                .foregroundStyle(Color(red: 0.30, green: 0.30, blue: 0.30))
        }
        .font(.caption)
        .padding(.horizontal, 16)
        .padding(.vertical, 8)
        .background(Color(red: 0.95, green: 0.95, blue: 0.98))
    }
}

// MARK: - Owner info strip

struct OwnerInfoStrip: View {
    let name: String
    let address: String

    var body: some View {
        HStack(alignment: .top) {
            VStack(alignment: .leading, spacing: 3) {
                if !name.isEmpty {
                    Text(name)
                        .bold()
                        .font(.subheadline)
                        .foregroundStyle(Color(red: 0.10, green: 0.10, blue: 0.25))
                }
                if !address.isEmpty {
                    Text(address)
                        .font(.caption)
                        .foregroundStyle(Color(red: 0.35, green: 0.35, blue: 0.45))
                        .lineLimit(4)
                }
            }
            Spacer()
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 10)
        .background(Color(red: 0.96, green: 0.96, blue: 1.00))
        .overlay(alignment: .bottom) {
            Divider()
        }
    }
}

// MARK: - Item row sub-views

private struct ItemThumbnail: View {
    let item: InventoryItem

    var body: some View {
        Group {
            if let data = item.imageData, let uiImage = UIImage(data: data) {
                Image(uiImage: uiImage)
                    .resizable()
                    .scaledToFill()
            } else {
                ZStack {
                    Color(red: 0.28, green: 0.12, blue: 0.72).opacity(0.10)
                    Image(systemName: item.category?.sfSymbol ?? "square.grid.2x2")
                        .foregroundStyle(Color(red: 0.28, green: 0.12, blue: 0.72))
                        .font(.system(size: 15))
                }
            }
        }
        .frame(width: 34, height: 34)
        .clipShape(.rect(cornerRadius: 6))
    }
}

private struct ItemInfo: View {
    let item: InventoryItem

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(item.name.isEmpty ? "Unnamed" : item.name)
                .bold()
                .font(.subheadline)
                .foregroundStyle(.primary)
            HStack(spacing: 4) {
                if let category = item.category {
                    Label(category.name, systemImage: category.sfSymbol)
                }
                if let brand = item.brand {
                    Text("·")
                    Text(brand.name)
                }
            }
            .font(.caption)
            .foregroundStyle(Color(red: 0.35, green: 0.35, blue: 0.35))
        }
    }
}

private struct ItemPriceStack: View {
    let item: InventoryItem

    var body: some View {
        VStack(alignment: .trailing, spacing: 2) {
            Text(item.price, format: .currency(code: Locale.current.currency?.identifier ?? "USD"))
                .bold()
                .font(.subheadline)
            if item.warrantyMonths > 0 {
                Text("\(item.warrantyMonths) mo. warranty")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }
}

// MARK: - Item row

private struct ReportItemRow: View {
    let item: InventoryItem
    let isAlternate: Bool

    var body: some View {
        HStack(spacing: 10) {
            ItemThumbnail(item: item)
            ItemInfo(item: item)
            Spacer()
            ItemPriceStack(item: item)
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 9)
        .background(isAlternate ? Color(red: 0.96, green: 0.96, blue: 1.00) : .white)
    }
}

// MARK: - Top-level report view

// MARK: - Preview

struct ReportContentPreview: View {
    @Query(sort: \InventoryItem.name) private var items: [InventoryItem]

    var body: some View {
        ScrollView([.horizontal, .vertical]) {
            InventoryReportContent(items: items)
                .frame(width: 595)
        }
    }
}

#Preview {
    let config = ModelConfiguration(isStoredInMemoryOnly: true)
    let container = try! ModelContainer(for: InventoryItem.self, configurations: config)
    SampleDataGenerator.generate(in: container.mainContext)
    return ReportContentPreview()
        .modelContainer(container)
}

// MARK: - Top-level report view

struct InventoryReportContent: View {
    let items: [InventoryItem]
    var showPageDecorations: Bool = true
    var ownerName: String = ""
    var ownerAddress: String = ""

    private var groupedByRoom: [(room: Room?, items: [InventoryItem])] {
        let dict = Dictionary(grouping: items) { $0.room }
        return dict
            .sorted { a, b in
                switch (a.key?.name, b.key?.name) {
                case (let n1?, let n2?): return n1 < n2
                case (nil, _): return false
                case (_, nil): return true
                }
            }
            .map { (room: $0.key, items: $0.value.sorted { $0.name < $1.name }) }
    }

    private var hasOwnerInfo: Bool { !ownerName.isEmpty || !ownerAddress.isEmpty }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            if showPageDecorations {
                ReportHeader(items: items)
            }
            if hasOwnerInfo {
                OwnerInfoStrip(name: ownerName, address: ownerAddress)
            }
            ForEach(groupedByRoom, id: \.room?.name) { group in
                roomSection(room: group.room, items: group.items)
            }
            if showPageDecorations {
                ReportFooter()
            }
        }
        .background(.white)
    }

    // MARK: - Room sections

    private func roomSection(room: Room?, items: [InventoryItem]) -> some View {
        VStack(alignment: .leading, spacing: 0) {
            // Section header bar
            HStack(spacing: 8) {
                if let data = room?.photoData, let uiImage = UIImage(data: data) {
                    Image(uiImage: uiImage)
                        .resizable()
                        .scaledToFill()
                        .frame(width: 22, height: 22)
                        .clipShape(.circle)
                } else {
                    Image(systemName: room?.sfSymbol ?? "house")
                        .foregroundStyle(.white)
                        .font(.system(size: 13))
                }
                Text(room?.name ?? "Unassigned")
                    .bold()
                    .foregroundStyle(.white)
                    .font(.subheadline)
                Spacer()
                Text("^[\(items.count) item](inflect: true)")
                    .foregroundStyle(.white.opacity(0.80))
                    .font(.caption)
            }
            .padding(.horizontal, 14)
            .padding(.vertical, 7)
            .background(Color(red: 0.28, green: 0.12, blue: 0.72).opacity(0.82))

            // Item rows
            ForEach(items.enumerated(), id: \.element.id) { index, item in
                ReportItemRow(item: item, isAlternate: index.isMultiple(of: 2))
                if index < items.count - 1 {
                    Divider().padding(.leading, 58)
                }
            }
        }
    }
}
